/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.BancoReserva;
import controller.ControleFuncionario;
import controller.ControleSenha;
import model.Funcionario;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.JPasswordField;

/**
 *
 * @author edson
 */
public class TelaAlterarCadastro extends javax.swing.JFrame {
    
    boolean logado;
    String senha;
    
    /**
     * Creates new form TelaAlterarReserva
     */
    public TelaAlterarCadastro(Funcionario f, boolean isAdministrador) {
        initComponents();
        iconeTitulo();
        perguntarSair();
        corFundo();
        cp_nomeFuncionarioAlterar.setText(f.getNome());
        cp_siapeFuncionarioAlterar.setValue(f.getSiape());
        cp_cargoFuncionarioAlterar.setSelectedItem(f.getCargo());
        cp_senhaFuncionarioAlterar.setText("SUASENHAAQUI");
        if(f.isAdmin()){
            cp_administradorSim.setSelected(true);
        }else{
            cp_administradorNao.setSelected(true);
        }
        
        if(!isAdministrador){
            cp_siapeFuncionarioAlterar.setEnabled(false);
            cp_cargoFuncionarioAlterar.setEnabled(false);
            cp_administradorNao.setEnabled(false);
            cp_administradorSim.setEnabled(false);
        }
        //logado = f.isLogado();
        senha = f.getSenha();
        
    }

    public void corFundo() {
        this.getContentPane().setBackground(new Color(102, 102, 102));
        bt_cancelarAlterar.setBackground(new Color(255, 255, 255));
        bt_salvarAlteracao.setBackground(new Color(255, 255, 255));
    }

    public void iconeTitulo() {
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image imagem = kit.getImage(getClass().getResource("/view/imagens/logoTitulo.png"));
        setIconImage(imagem);
    }

    public void perguntarSair() {
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (e.getID() == WindowEvent.WINDOW_CLOSING) {
                    int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
                    if (selectedOption == JOptionPane.YES_OPTION) {
                        dispose();
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoAdministrador = new javax.swing.ButtonGroup();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cp_cargoFuncionarioAlterar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_cancelarAlterar = new javax.swing.JButton();
        bt_salvarAlteracao = new javax.swing.JButton();
        cp_administradorSim = new javax.swing.JRadioButton();
        cp_administradorNao = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        cp_siapeFuncionarioAlterar = new javax.swing.JFormattedTextField();
        cp_nomeFuncionarioAlterar = new javax.swing.JTextField();
        cp_senhaFuncionarioAlterar = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Alterar Cadastro - Control Lab");
        setUndecorated(true);

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Siape");

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Cargo:");

        cp_cargoFuncionarioAlterar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_cargoFuncionarioAlterar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "Docente", "Técnico", "Outros" }));
        cp_cargoFuncionarioAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_cargoFuncionarioAlterarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha:");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");

        bt_cancelarAlterar.setBackground(new java.awt.Color(51, 51, 51));
        bt_cancelarAlterar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_cancelarAlterar.setText("Cancelar");
        bt_cancelarAlterar.setBorder(null);
        bt_cancelarAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_cancelarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarAlterarActionPerformed(evt);
            }
        });

        bt_salvarAlteracao.setBackground(new java.awt.Color(51, 51, 51));
        bt_salvarAlteracao.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_salvarAlteracao.setText("Salvar");
        bt_salvarAlteracao.setBorder(null);
        bt_salvarAlteracao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_salvarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarAlteracaoActionPerformed(evt);
            }
        });

        grupoAdministrador.add(cp_administradorSim);
        cp_administradorSim.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_administradorSim.setText("Sim");

        grupoAdministrador.add(cp_administradorNao);
        cp_administradorNao.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_administradorNao.setSelected(true);
        cp_administradorNao.setText("Não");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Administrador");

        try {
            cp_siapeFuncionarioAlterar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cp_siapeFuncionarioAlterar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N

        cp_nomeFuncionarioAlterar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N

        cp_senhaFuncionarioAlterar.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        cp_senhaFuncionarioAlterar.setMaximumSize(new java.awt.Dimension(6, 22));
        cp_senhaFuncionarioAlterar.setMinimumSize(new java.awt.Dimension(6, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cp_nomeFuncionarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cp_siapeFuncionarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cp_cargoFuncionarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(cp_senhaFuncionarioAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(cp_administradorSim)
                                    .addGap(18, 18, 18)
                                    .addComponent(cp_administradorNao)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(bt_cancelarAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_salvarAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cp_nomeFuncionarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cp_siapeFuncionarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cp_cargoFuncionarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cp_senhaFuncionarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cp_administradorSim)
                    .addComponent(cp_administradorNao)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_salvarAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cancelarAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cancelarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarAlterarActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_bt_cancelarAlterarActionPerformed

    private void bt_salvarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarAlteracaoActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar esse cadastro?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {
            
            String msg = "";
            String nome = cp_nomeFuncionarioAlterar.getText();
            String siape = cp_siapeFuncionarioAlterar.getValue().toString();
            String cargo = cp_cargoFuncionarioAlterar.getSelectedItem().toString();
            String senhaCampo = new String (cp_senhaFuncionarioAlterar.getPassword()).trim();
            
            if(!senhaCampo.equals("SUASENHAAQUI")){
                senha = controleSenha.criptografar(senhaCampo);
            }
            
            boolean administrador = false;
            if(cp_administradorSim.isSelected()){
                administrador = true;
            }
            
            //Mostrar campo de senha no JOptionPane
            JLabel label = new JLabel("Confirme sua senha:");
            JPasswordField jpf = new JPasswordField();
            JOptionPane.showConfirmDialog(null, new Object[]{label, jpf}, "Confirme sua senha", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            String senhaDigitada = new String(jpf.getPassword());
            
            if(controleSenha.criptografar(senhaDigitada).equals(senha)){
                
                msg = controleFuncionario.alterar(nome, siape, cargo, senha, administrador,logado);
                JOptionPane.showMessageDialog(this, msg);

                if(msg == "Cadastro alterado com sucesso!"){
                    dispose();
                }
                
            }else{
                JOptionPane.showMessageDialog(this, "Senhas não coincidem.", "Control Lab Avisa", WARNING_MESSAGE);
            }   
        }
    }//GEN-LAST:event_bt_salvarAlteracaoActionPerformed

    private void cp_cargoFuncionarioAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_cargoFuncionarioAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_cargoFuncionarioAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaAlterarReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelarAlterar;
    private javax.swing.JButton bt_salvarAlteracao;
    private javax.swing.JRadioButton cp_administradorNao;
    private javax.swing.JRadioButton cp_administradorSim;
    private javax.swing.JComboBox<String> cp_cargoFuncionarioAlterar;
    private javax.swing.JTextField cp_nomeFuncionarioAlterar;
    private javax.swing.JPasswordField cp_senhaFuncionarioAlterar;
    private javax.swing.JFormattedTextField cp_siapeFuncionarioAlterar;
    private javax.swing.ButtonGroup grupoAdministrador;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
    BancoReserva bancoReserva = new BancoReserva();
    ControleFuncionario controleFuncionario = new ControleFuncionario();
    ControleSenha controleSenha = new ControleSenha();
}
