/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.BancoFuncionario;
import controller.ControleFeedback;
import controller.ControleReserva;
import controller.ControleFuncionario;
import controller.ControleRelatorio;
import controller.ControleVariaveis;
import model.Feedback;
import model.Funcionario;
import model.Reserva;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edson
 */
public class TelaPrincipalAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalOutros
     */
    public TelaPrincipalAdministrador() {
        initComponents();
        iconeTitulo();
        tituloTabela();
        perguntarSair();
        corFundo();
        preencherFuncionario(bancoFuncionario.listar());
        preencherTabelaReserva(controleReserva.pesquisar(""));
        preencherTabelaFeedback(controleFeedback.atualizar(""));
        cancelarReserva.setText("Cancelar Reserva");
        alterarReserva.setText("Alterar Reserva");
        cancelarFeedback.setText("Apagar Feedback");
        alterarStatus.setText("Alterar Status");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuReserva = new javax.swing.JPopupMenu();
        cancelarReserva = new javax.swing.JMenuItem();
        alterarReserva = new javax.swing.JMenuItem();
        menuFeedback = new javax.swing.JPopupMenu();
        cancelarFeedback = new javax.swing.JMenuItem();
        alterarStatus = new javax.swing.JMenuItem();
        grupoRelatorioFeedbackReserva = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cp_proposito = new javax.swing.JTextPane();
        bt_cadastrarReserva = new javax.swing.JButton();
        bt_limparReserva = new javax.swing.JButton();
        cp_horaEntrada = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cp_minutoEntrada = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cp_horaSaida = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cp_minutoSaida = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cp_dataReserva = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        cp_laboratorioReserva = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cp_listarFuncionarios = new javax.swing.JComboBox<>();
        txt_nomeFuncionarioCadReserva = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_siapeCadReserva = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bt_cadastrarFuncionario = new javax.swing.JButton();
        bt_limparFuncionario = new javax.swing.JButton();
        cp_nome = new javax.swing.JTextField();
        cp_cargo = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        cp_senhaFuncionario = new javax.swing.JPasswordField();
        cp_tornarAdministrador = new javax.swing.JCheckBox();
        cp_siapeFuncionario = new javax.swing.JFormattedTextField();
        txt_nomeFuncionarioCadFuncionario = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_siapeCadFuncionario = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cp_tabelaReservas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        bt_pesquisar = new javax.swing.JToggleButton();
        cp_pesquisar = new javax.swing.JTextField();
        bt_atualizarTelaReservas = new javax.swing.JToggleButton();
        txt_nomeFuncionarioConsReserva = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_siapeConsReserva = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        cp_tabelaFeedback = new javax.swing.JTable();
        bt_atualizar = new javax.swing.JButton();
        txt_nomeFuncionarioConsFeedback = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_siapeConsFeedback = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        bt_gerarRelatorio = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bt_reservas = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        cp_dataInicial = new com.toedter.calendar.JDateChooser();
        cp_dataFinal = new com.toedter.calendar.JDateChooser();
        txt_nomeFuncionarioRelatorio = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_siapeRelatorio = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        bt_finalizarSistema = new javax.swing.JButton();
        bt_alterarSenhaAdministrador = new javax.swing.JButton();
        bt_apagarcadastroFuncionario = new javax.swing.JButton();
        bt_alterarCadastroFuncionario = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        txt_nomeFuncionarioOpcoes = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt_siapeOpcoes = new javax.swing.JLabel();

        cancelarReserva.setText("jMenuItem1");
        cancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarReservaActionPerformed(evt);
            }
        });
        menuReserva.add(cancelarReserva);

        alterarReserva.setText("jMenuItem1");
        alterarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarReservaActionPerformed(evt);
            }
        });
        menuReserva.add(alterarReserva);

        cancelarFeedback.setText("jMenuItem1");
        cancelarFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarFeedbackActionPerformed(evt);
            }
        });
        menuFeedback.add(cancelarFeedback);

        alterarStatus.setText("jMenuItem1");
        alterarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarStatusActionPerformed(evt);
            }
        });
        menuFeedback.add(alterarStatus);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal - Administrador");
        setExtendedState(this.MAXIMIZED_BOTH);

        jTabbedPane1.setFont(new java.awt.Font("GillSans", 0, 18)); // NOI18N

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preencha os campos abaixo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 15))); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 350));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel3.setText("h");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel4.setText("Horário de Saída:");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel5.setText("Propósito:");

        cp_proposito.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jScrollPane1.setViewportView(cp_proposito);

        bt_cadastrarReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_cadastrarReserva.setText("Cadastrar");
        bt_cadastrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarReservaActionPerformed(evt);
            }
        });

        bt_limparReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_limparReserva.setText("Limpar");
        bt_limparReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparReservaActionPerformed(evt);
            }
        });

        cp_horaEntrada.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_horaEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cp_horaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_horaEntradaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel17.setText("Horário de Entrada:");

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel18.setText("min");

        cp_minutoEntrada.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_minutoEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cp_minutoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_minutoEntradaActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel19.setText("h");

        cp_horaSaida.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_horaSaida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cp_horaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_horaSaidaActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel20.setText("min");

        cp_minutoSaida.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_minutoSaida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cp_minutoSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_minutoSaidaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel2.setText("Data da Reserva:");

        cp_dataReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel23.setText("Laboratório:");

        cp_laboratorioReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_laboratorioReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "Informática - BLOCO A", "Informática - BLOCO B", "Informática - BLOCO C", "Redes - BLOCO A" }));
        cp_laboratorioReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_laboratorioReservaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel21.setText("Funcionário:");

        cp_listarFuncionarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_listarFuncionarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista de Funcionários" }));
        cp_listarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_listarFuncionariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cp_horaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cp_minutoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cp_horaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cp_minutoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel21))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cp_dataReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cp_listarFuncionarios, 0, 376, Short.MAX_VALUE)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(bt_cadastrarReserva)
                                    .addGap(46, 46, 46)
                                    .addComponent(bt_limparReserva))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addGap(70, 70, 70)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(cp_laboratorioReserva, 0, 375, Short.MAX_VALUE)))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cp_listarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(cp_dataReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel17))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cp_horaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(cp_minutoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(cp_horaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(cp_minutoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cp_laboratorioReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_limparReserva)
                    .addComponent(bt_cadastrarReserva))
                .addContainerGap())
        );

        txt_nomeFuncionarioCadReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_nomeFuncionarioCadReserva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_nomeFuncionarioCadReserva.setText("Nome Completo do Funcionario");

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel25.setText("|");

        txt_siapeCadReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_siapeCadReserva.setText("1234567");

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeBackground.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addComponent(txt_nomeFuncionarioCadReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_siapeCadReserva)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_nomeFuncionarioCadReserva)
                                .addComponent(jLabel25)
                                .addComponent(txt_siapeCadReserva)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(428, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Reserva", new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeCadastrarReserva.png")), jPanel1); // NOI18N

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preencha os campos abaixo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 15))); // NOI18N
        jPanel9.setPreferredSize(new java.awt.Dimension(500, 350));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel6.setText("Siape:");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel7.setText("Nome:");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel8.setText("Cargo:");

        bt_cadastrarFuncionario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_cadastrarFuncionario.setText("Cadastrar");
        bt_cadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarFuncionarioActionPerformed(evt);
            }
        });

        bt_limparFuncionario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_limparFuncionario.setText("Limpar");
        bt_limparFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparFuncionarioActionPerformed(evt);
            }
        });

        cp_nome.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N

        cp_cargo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Docente", "Técnico", "Outros" }));
        cp_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_cargoActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel22.setText("Senha:");

        cp_senhaFuncionario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_senhaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_senhaFuncionarioActionPerformed(evt);
            }
        });

        cp_tornarAdministrador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        cp_tornarAdministrador.setText("Tornar esse funcionário um administrador");
        cp_tornarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_tornarAdministradorActionPerformed(evt);
            }
        });

        try {
            cp_siapeFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cp_siapeFuncionario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_cadastrarFuncionario)
                .addGap(54, 54, 54)
                .addComponent(bt_limparFuncionario)
                .addGap(88, 88, 88))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addGap(19, 19, 19)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cp_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cp_siapeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cp_senhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cp_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cp_tornarAdministrador))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cp_siapeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cp_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cp_senhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cp_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(cp_tornarAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cadastrarFuncionario)
                    .addComponent(bt_limparFuncionario))
                .addGap(22, 22, 22))
        );

        txt_nomeFuncionarioCadFuncionario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_nomeFuncionarioCadFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_nomeFuncionarioCadFuncionario.setText("Nome Completo do Funcionario");

        jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel26.setText("|");

        txt_siapeCadFuncionario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_siapeCadFuncionario.setText("1234567");

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeBackground.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                        .addComponent(txt_nomeFuncionarioCadFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_siapeCadFuncionario)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel33)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nomeFuncionarioCadFuncionario)
                            .addComponent(jLabel26)
                            .addComponent(txt_siapeCadFuncionario))
                        .addGap(132, 132, 132)
                        .addComponent(jLabel33)))
                .addContainerGap(567, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Funcionário", new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeCadastrarFuncionario.png")), jPanel2); // NOI18N

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fazer busca nas consultas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 15))); // NOI18N

        cp_tabelaReservas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cp_tabelaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data", "Laboratório", "Horário", "Propósito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cp_tabelaReservas.setToolTipText("");
        cp_tabelaReservas.setName(""); // NOI18N
        cp_tabelaReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cp_tabelaReservasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cp_tabelaReservas);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel9.setText("Pesquisar:");

        bt_pesquisar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        cp_pesquisar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_pesquisarActionPerformed(evt);
            }
        });

        bt_atualizarTelaReservas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_atualizarTelaReservas.setText("Atualizar");
        bt_atualizarTelaReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarTelaReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cp_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(bt_pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_atualizarTelaReservas)))
                .addContainerGap(616, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cp_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_pesquisar)
                    .addComponent(bt_atualizarTelaReservas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_nomeFuncionarioConsReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_nomeFuncionarioConsReserva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_nomeFuncionarioConsReserva.setText("Nome Completo do Funcionario");

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel24.setText("|");

        txt_siapeConsReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_siapeConsReserva.setText("1234567");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_nomeFuncionarioConsReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_siapeConsReserva)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nomeFuncionarioConsReserva)
                    .addComponent(jLabel24)
                    .addComponent(txt_siapeConsReserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar Reservas", new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeConsultarReservas.png")), jPanel3); // NOI18N

        jScrollPane5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cp_tabelaFeedback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cp_tabelaFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Funcionário", "Laboratorio", "Data", "Descrição", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cp_tabelaFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cp_tabelaFeedbackMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(cp_tabelaFeedback);

        bt_atualizar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_atualizar.setText("Atualizar");
        bt_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarActionPerformed(evt);
            }
        });

        txt_nomeFuncionarioConsFeedback.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_nomeFuncionarioConsFeedback.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_nomeFuncionarioConsFeedback.setText("Nome Completo do Funcionario");

        jLabel28.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel28.setText("|");

        txt_siapeConsFeedback.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_siapeConsFeedback.setText("1234567");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_atualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 671, Short.MAX_VALUE)
                .addComponent(txt_nomeFuncionarioConsFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_siapeConsFeedback)
                .addGap(24, 24, 24))
            .addComponent(jScrollPane5)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nomeFuncionarioConsFeedback)
                        .addComponent(jLabel28)
                        .addComponent(txt_siapeConsFeedback))
                    .addComponent(bt_atualizar))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar FeedBack's", new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeFeedback.png")), jPanel6); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerar Relatórios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 15))); // NOI18N

        bt_gerarRelatorio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_gerarRelatorio.setText("Gerar Relatório");
        bt_gerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gerarRelatorioActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel13.setText("Data Inicial:");

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel14.setText("Data Final:");

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel16.setText("Relatório:");

        grupoRelatorioFeedbackReserva.add(bt_reservas);
        bt_reservas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_reservas.setSelected(true);
        bt_reservas.setText("Reservas");

        grupoRelatorioFeedbackReserva.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jRadioButton2.setText("Feedbacks");

        cp_dataInicial.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_reservas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(121, 121, 121))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(bt_gerarRelatorio))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cp_dataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cp_dataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14)
                        .addComponent(cp_dataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cp_dataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addGap(50, 50, 50)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(bt_reservas)
                    .addComponent(jRadioButton2))
                .addGap(50, 50, 50)
                .addComponent(bt_gerarRelatorio)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        txt_nomeFuncionarioRelatorio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_nomeFuncionarioRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_nomeFuncionarioRelatorio.setText("Nome Completo do Funcionario");

        jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel29.setText("|");

        txt_siapeRelatorio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_siapeRelatorio.setText("1234567");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeBackground.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addComponent(txt_nomeFuncionarioRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_siapeRelatorio)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel32)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nomeFuncionarioRelatorio)
                            .addComponent(jLabel29)
                            .addComponent(txt_siapeRelatorio))
                        .addGap(160, 160, 160)
                        .addComponent(jLabel32)))
                .addContainerGap(538, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatório", new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeRelatorio.png")), jPanel5); // NOI18N

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecione alguma opção abaixo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 15))); // NOI18N

        bt_finalizarSistema.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_finalizarSistema.setText("Sair");
        bt_finalizarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_finalizarSistemaActionPerformed(evt);
            }
        });

        bt_alterarSenhaAdministrador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_alterarSenhaAdministrador.setText("Alterar Senha Administrativa");
        bt_alterarSenhaAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarSenhaAdministradorActionPerformed(evt);
            }
        });

        bt_apagarcadastroFuncionario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_apagarcadastroFuncionario.setText("Apagar Cadastro dos Funcionários");
        bt_apagarcadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_apagarcadastroFuncionarioActionPerformed(evt);
            }
        });

        bt_alterarCadastroFuncionario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_alterarCadastroFuncionario.setText("Alterar Cadastro dos Funcionários");
        bt_alterarCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarCadastroFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bt_finalizarSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_alterarSenhaAdministrador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_apagarcadastroFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_alterarCadastroFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(bt_alterarCadastroFuncionario)
                .addGap(35, 35, 35)
                .addComponent(bt_apagarcadastroFuncionario)
                .addGap(39, 39, 39)
                .addComponent(bt_alterarSenhaAdministrador)
                .addGap(34, 34, 34)
                .addComponent(bt_finalizarSistema)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeBackground.png"))); // NOI18N

        txt_nomeFuncionarioOpcoes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_nomeFuncionarioOpcoes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_nomeFuncionarioOpcoes.setText("Nome Completo do Funcionario");

        jLabel35.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel35.setText("|");

        txt_siapeOpcoes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_siapeOpcoes.setText("1234567");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel30)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                        .addComponent(txt_nomeFuncionarioOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_siapeOpcoes)
                        .addGap(34, 34, 34))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nomeFuncionarioOpcoes)
                            .addComponent(jLabel35)
                            .addComponent(txt_siapeOpcoes))
                        .addGap(175, 175, 175)
                        .addComponent(jLabel30)))
                .addContainerGap(534, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Opções", new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeOpcao.png")), jPanel10); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void preencherFuncionario(List<Funcionario> funcionarios) {
        cp_listarFuncionarios.removeAllItems();
        for (Funcionario array : funcionarios) {
            cp_listarFuncionarios.addItem(array.getNome());
        }
    }

    public void tituloTabela() {
        cp_tabelaReservas.getTableHeader().setFont(new Font("Arial Rounded MT Bold", 0, 15));
        cp_tabelaFeedback.getTableHeader().setFont(new Font("Arial Rounded MT Bold", 0, 15));
    }

    public void iconeTitulo() {
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image imagem = kit.getImage(getClass().getResource("/view/imagens/logoTitulo.png"));
        setIconImage(imagem);
    }

    public void corFundo() {
        this.getContentPane().setBackground(new Color(102, 102, 102));
    }

    public void perguntarSair() {
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (e.getID() == WindowEvent.WINDOW_CLOSING) {
                    int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
                    if (selectedOption == JOptionPane.YES_OPTION) {
                        System.exit(0);
                    }
                }
            }
        });
    }

    public void preencherTop(ControleVariaveis controleVariaveis) {
        txt_nomeFuncionarioConsReserva.setText(controleVariaveis.getNomeTop());
        txt_nomeFuncionarioCadReserva.setText(controleVariaveis.getNomeTop());
        txt_nomeFuncionarioCadFuncionario.setText(controleVariaveis.getNomeTop());
        txt_nomeFuncionarioConsFeedback.setText(controleVariaveis.getNomeTop());
        txt_nomeFuncionarioRelatorio.setText(controleVariaveis.getNomeTop());
        txt_nomeFuncionarioOpcoes.setText(controleVariaveis.getNomeTop());
        txt_siapeConsReserva.setText(controleVariaveis.getSiapeTop());
        txt_siapeCadReserva.setText(controleVariaveis.getSiapeTop());
        txt_siapeCadFuncionario.setText(controleVariaveis.getSiapeTop());
        txt_siapeConsFeedback.setText(controleVariaveis.getSiapeTop());
        txt_siapeRelatorio.setText(controleVariaveis.getSiapeTop());
        txt_siapeOpcoes.setText(controleVariaveis.getSiapeTop());
    }

    private void cancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarReservaActionPerformed
        // TODO add your handling code here:

        int selectedOption = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar essa reserva?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {
            String msg = controleReserva.cancelarReserva(reservaRecuperada);
            JOptionPane.showMessageDialog(null, msg, "Control Lab Avisa", INFORMATION_MESSAGE);
            List<Reserva> lista = controleReserva.pesquisar("");
            preencherTabelaReserva(lista);
        }

    }//GEN-LAST:event_cancelarReservaActionPerformed

    private void alterarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarReservaActionPerformed
        // TODO add your handling code here:
        new TelaAlterarReserva(reservaRecuperada).setVisible(true);
    }//GEN-LAST:event_alterarReservaActionPerformed

    private void cancelarFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarFeedbackActionPerformed

        int selectedOption = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar essa reserva?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {
            String msg = controleFeedback.removerFeedback(feedbackRecuperado);
            JOptionPane.showMessageDialog(null, msg, "Control Lab Avisa", INFORMATION_MESSAGE);
            preencherTabelaFeedback(controleFeedback.atualizar(""));
        }

    }//GEN-LAST:event_cancelarFeedbackActionPerformed

    private void bt_alterarCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarCadastroFuncionarioActionPerformed

        new TelaSelecionarFuncionarioAlterar().setVisible(true);

    }//GEN-LAST:event_bt_alterarCadastroFuncionarioActionPerformed

    private void bt_apagarcadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_apagarcadastroFuncionarioActionPerformed

        new TelaSelecionarFuncionarioApagar().setVisible(true);
    }//GEN-LAST:event_bt_apagarcadastroFuncionarioActionPerformed

    private void bt_alterarSenhaAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarSenhaAdministradorActionPerformed

        new TelaAlterarSenhaAdministrativa().setVisible(true);
    }//GEN-LAST:event_bt_alterarSenhaAdministradorActionPerformed

    private void bt_finalizarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_finalizarSistemaActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente voltar para a tela de login?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);

        if (resposta == JOptionPane.YES_OPTION) {
            new TelaLogin().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_bt_finalizarSistemaActionPerformed

    private void bt_gerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gerarRelatorioActionPerformed
        // TODO add your handling code here:

        if (cp_dataInicial.getDate() == null || cp_dataFinal.getDate() == null) {

            JOptionPane.showMessageDialog(null, "Verifique se as datas estão corretas!", "Control Lab Avisa", INFORMATION_MESSAGE);

        } else {

            Date auxdataInicial = cp_dataInicial.getDate();
            Date auxdataFinal = cp_dataFinal.getDate();

            if (auxdataInicial.after(auxdataFinal)) {
                
                JOptionPane.showMessageDialog(null, "A Data Inicial não pode ser maior que a Data Final", "Control Lab Avisa", QUESTION_MESSAGE);
            
            } else {
                boolean tipoRelatorio = bt_reservas.isSelected();

                String dataInicial = converteData.format(auxdataInicial);
                String dataFinal = converteData.format(auxdataFinal);

                System.out.println("Data inicial: " + auxdataInicial);
                System.out.println("Data final: " + auxdataFinal);
                System.out.println("Data inicial Conv: " + dataInicial);
                System.out.println("Data final Conv: " + dataFinal);

                try {
                controleRelatorio.gerarRelatorio(converteData.parse(dataInicial), converteData.parse(dataFinal), tipoRelatorio);
                } catch (Exception ex) {
                    System.out.println("Erro ao gerar relatório!\n" + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_bt_gerarRelatorioActionPerformed

    private void bt_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarActionPerformed
        // TODO add your handling code here:

        preencherTabelaFeedback(controleFeedback.atualizar(""));

    }//GEN-LAST:event_bt_atualizarActionPerformed

    private void cp_tabelaFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cp_tabelaFeedbackMouseClicked

        DefaultTableModel modelo = (DefaultTableModel) cp_tabelaFeedback.getModel();

        if (evt.getButton() == MouseEvent.BUTTON3 && cp_tabelaFeedback.getSelectedRowCount() == 1) {
            try {
                int x = evt.getX();
                int y = evt.getY();

                int linha = cp_tabelaFeedback.getSelectedRow();

                menuFeedback.show(cp_tabelaFeedback, x, y);
                feedbackRecuperado = controleFeedback.recuperarCancelarFeedback(linha);

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro : " + erro, "Control Lab Avisa", ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_cp_tabelaFeedbackMouseClicked

    private void bt_atualizarTelaReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarTelaReservasActionPerformed
        // TODO add your handling code here:

        ControleVariaveis controleVariaveis = new ControleVariaveis();
        controleVariaveis.setNomeTop(txt_nomeFuncionarioConsReserva.getText());
        controleVariaveis.setSiapeTop(txt_siapeConsReserva.getText());

        TelaPrincipalAdministrador telaPrincipalAdministrador = new TelaPrincipalAdministrador();
        telaPrincipalAdministrador.preencherTop(controleVariaveis);
        telaPrincipalAdministrador.setVisible(true);

        dispose();
    }//GEN-LAST:event_bt_atualizarTelaReservasActionPerformed

    private void cp_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_pesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_pesquisarActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        // TODO add your handling code here:
        String pesquisa = cp_pesquisar.getText();
        List<Reserva> Lista = controleReserva.pesquisar(pesquisa);
        preencherTabelaReserva(Lista);
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void cp_tabelaReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cp_tabelaReservasMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) cp_tabelaReservas.getModel();

        if (evt.getButton() == MouseEvent.BUTTON3 && cp_tabelaReservas.getSelectedRowCount() == 1) {
            try {
                int x = evt.getX();
                int y = evt.getY();
                menuReserva.show(cp_tabelaReservas, x, y);

                int linha = cp_tabelaReservas.getSelectedRow();
                Date data = converteData.parse(modelo.getValueAt(linha, 1).toString());
                String horarioAux = modelo.getValueAt(linha, 3).toString();

                Date horaEntrada = converteHora.parse(horarioAux.substring(3, 8));
                Date horaSaida = converteHora.parse(horarioAux.substring(13));

                reservaRecuperada = controleReserva.recuperarReserva(data, horaEntrada, horaSaida);

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro : " + erro, "Control Lab Avisa", ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_cp_tabelaReservasMouseClicked

    private void cp_tornarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_tornarAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_tornarAdministradorActionPerformed

    private void cp_senhaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_senhaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_senhaFuncionarioActionPerformed

    private void cp_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_cargoActionPerformed

    private void bt_limparFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparFuncionarioActionPerformed
        // TODO add your handling code here:
        cp_siapeFuncionario.setText(null);
        cp_nome.setText("");
        cp_senhaFuncionario.setText("");
        cp_cargo.setSelectedItem("-----------");
    }//GEN-LAST:event_bt_limparFuncionarioActionPerformed

    private void bt_cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarFuncionarioActionPerformed
        // TODO add your handling code here

        int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente cadastrar esse Funcionado?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {

            String senha = new String(cp_senhaFuncionario.getPassword()).trim();
            boolean administrador = cp_tornarAdministrador.isSelected();
            String nome = cp_nome.getText();
            String cargo = cp_cargo.getSelectedItem().toString();

            String siape = "";

            if (!cp_siapeFuncionario.getText().trim().isEmpty()) {
                siape = cp_siapeFuncionario.getValue().toString();
            }

            String msg = controleFuncionario.salvar(siape, nome, cargo, senha, administrador);
            JOptionPane.showMessageDialog(this, msg);

            if (msg.equals("Funcionário cadastrado com sucesso!")) {
                cp_siapeFuncionario.setValue(null);
                cp_nome.setText("");
                cp_cargo.setSelectedItem("-----------");
                cp_senhaFuncionario.setText("");
                cp_tornarAdministrador.setSelected(false);
                preencherFuncionario(bancoFuncionario.listar());
            }
        }
    }//GEN-LAST:event_bt_cadastrarFuncionarioActionPerformed

    private void cp_listarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_listarFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_listarFuncionariosActionPerformed

    private void cp_laboratorioReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_laboratorioReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_laboratorioReservaActionPerformed

    private void cp_minutoSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_minutoSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_minutoSaidaActionPerformed

    private void cp_horaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_horaSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_horaSaidaActionPerformed

    private void cp_minutoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_minutoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_minutoEntradaActionPerformed

    private void cp_horaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_horaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_horaEntradaActionPerformed

    private void bt_limparReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparReservaActionPerformed
        // TODO add your handling code here:

        cp_dataReserva.setDate(null);
        cp_horaEntrada.setSelectedItem("--");
        cp_minutoEntrada.setSelectedItem("--");
        cp_horaSaida.setSelectedItem("--");
        cp_minutoSaida.setSelectedItem("--");
        cp_proposito.setText("");
        cp_laboratorioReserva.setSelectedItem("-------");
        cp_listarFuncionarios.setSelectedIndex(0);
    }//GEN-LAST:event_bt_limparReservaActionPerformed

    private void bt_cadastrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarReservaActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente cadastrar essa reserva?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {

            if (cp_dataReserva.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!!");
            }

            String nome = cp_listarFuncionarios.getSelectedItem().toString();

            String siape = bancoFuncionario.recuperarSiape(nome);
            String msg = "";
            String proposito = cp_proposito.getText();
            String laboratorio = cp_laboratorioReserva.getSelectedItem().toString();

            Date auxDataReserva = cp_dataReserva.getDate();
            String aux2dataReserva = converteData.format(auxDataReserva);

            String horaEntrada = cp_horaEntrada.getSelectedItem().toString();
            String minutoEntrada = cp_minutoEntrada.getSelectedItem().toString();
            String horaSaida = cp_horaSaida.getSelectedItem().toString();
            String minutoSaida = cp_minutoSaida.getSelectedItem().toString();

            try {
                Date dataReserva = converteData.parse(aux2dataReserva);
                Date horarioEntradaReserva = converteHora.parse(horaEntrada + ":" + minutoEntrada);
                Date horarioSaidaReserva = converteHora.parse(horaSaida + ":" + minutoSaida);

                msg = controleReserva.cadastrar(nome, siape, dataReserva, horarioEntradaReserva, horarioSaidaReserva, proposito, laboratorio);
                JOptionPane.showMessageDialog(this, msg);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Data ou Hora inválidas!");
            }

            if (msg.equals("Reserva cadastrada com sucesso!")) {
                cp_dataReserva.setDate(null);
                cp_horaEntrada.setSelectedItem("--");
                cp_minutoEntrada.setSelectedItem("--");
                cp_horaSaida.setSelectedItem("--");
                cp_minutoSaida.setSelectedItem("--");
                cp_proposito.setText("");
                cp_laboratorioReserva.setSelectedItem("-------");
                List<Reserva> Lista = controleReserva.pesquisar("");
                preencherTabelaReserva(Lista);
            }
        }
    }//GEN-LAST:event_bt_cadastrarReservaActionPerformed

    private void alterarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarStatusActionPerformed

        int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar o status do Feedback selecionado?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {
            String[] status = {"Pendente", "Em andamento", "Finalizado", "Cancelado", "Inconsistente"};
            int indiceStatusAtual = 0;

            for (int i = 0; i < status.length; i++) {
                if (status[i].equals(feedbackRecuperado.getStatus())) {
                    indiceStatusAtual = i;
                    break;
                }
            }

            String novoStatus = (String) JOptionPane.showInputDialog(null,
                    "Feedback criado por: " + feedbackRecuperado.getSiape().getNome()
                    + "\n\nSeleciona um novo Status para o Feedback selecionado.", // Título
                    "Alterar Status do Feedback", // Subtítulo
                    JOptionPane.QUESTION_MESSAGE, null,
                    status, // Array com as opções
                    status[indiceStatusAtual]); // Padrão

            if (novoStatus != null && !novoStatus.isEmpty()) {

                Feedback feedback = feedbackRecuperado;
                feedback.setStatus(novoStatus);
                String msg = controleFeedback.alterar(feedback);

                JOptionPane.showMessageDialog(null, msg);

                if (msg.equals("Feedback alterado com sucesso!")) {
                    preencherTabelaFeedback(controleFeedback.atualizar(""));
                }
            }
        }
    }//GEN-LAST:event_alterarStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarReserva;
    private javax.swing.JMenuItem alterarStatus;
    private javax.swing.JButton bt_alterarCadastroFuncionario;
    private javax.swing.JButton bt_alterarSenhaAdministrador;
    private javax.swing.JButton bt_apagarcadastroFuncionario;
    private javax.swing.JButton bt_atualizar;
    private javax.swing.JToggleButton bt_atualizarTelaReservas;
    private javax.swing.JButton bt_cadastrarFuncionario;
    private javax.swing.JButton bt_cadastrarReserva;
    private javax.swing.JButton bt_finalizarSistema;
    private javax.swing.JButton bt_gerarRelatorio;
    private javax.swing.JButton bt_limparFuncionario;
    private javax.swing.JButton bt_limparReserva;
    private javax.swing.JToggleButton bt_pesquisar;
    private javax.swing.JRadioButton bt_reservas;
    private javax.swing.JMenuItem cancelarFeedback;
    private javax.swing.JMenuItem cancelarReserva;
    private javax.swing.JComboBox<String> cp_cargo;
    private com.toedter.calendar.JDateChooser cp_dataFinal;
    private com.toedter.calendar.JDateChooser cp_dataInicial;
    private com.toedter.calendar.JDateChooser cp_dataReserva;
    private javax.swing.JComboBox<String> cp_horaEntrada;
    private javax.swing.JComboBox<String> cp_horaSaida;
    private javax.swing.JComboBox<String> cp_laboratorioReserva;
    private javax.swing.JComboBox<String> cp_listarFuncionarios;
    private javax.swing.JComboBox<String> cp_minutoEntrada;
    private javax.swing.JComboBox<String> cp_minutoSaida;
    private javax.swing.JTextField cp_nome;
    private javax.swing.JTextField cp_pesquisar;
    private javax.swing.JTextPane cp_proposito;
    private javax.swing.JPasswordField cp_senhaFuncionario;
    private javax.swing.JFormattedTextField cp_siapeFuncionario;
    private javax.swing.JTable cp_tabelaFeedback;
    private javax.swing.JTable cp_tabelaReservas;
    private javax.swing.JCheckBox cp_tornarAdministrador;
    private javax.swing.ButtonGroup grupoRelatorioFeedbackReserva;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPopupMenu menuFeedback;
    private javax.swing.JPopupMenu menuReserva;
    private javax.swing.JLabel txt_nomeFuncionarioCadFuncionario;
    private javax.swing.JLabel txt_nomeFuncionarioCadReserva;
    private javax.swing.JLabel txt_nomeFuncionarioConsFeedback;
    private javax.swing.JLabel txt_nomeFuncionarioConsReserva;
    private javax.swing.JLabel txt_nomeFuncionarioOpcoes;
    private javax.swing.JLabel txt_nomeFuncionarioRelatorio;
    private javax.swing.JLabel txt_siapeCadFuncionario;
    private javax.swing.JLabel txt_siapeCadReserva;
    private javax.swing.JLabel txt_siapeConsFeedback;
    private javax.swing.JLabel txt_siapeConsReserva;
    private javax.swing.JLabel txt_siapeOpcoes;
    private javax.swing.JLabel txt_siapeRelatorio;
    // End of variables declaration//GEN-END:variables

    private void preencherTabelaReserva(List<Reserva> Lista) {
        DefaultTableModel modelo = (DefaultTableModel) cp_tabelaReservas.getModel();

        Object[] linha = new Object[5];

        modelo.setRowCount(0);
        for (Reserva reserva : Lista) {
            linha[0] = reserva.getSiape().getNome();
            linha[1] = converteData.format(reserva.getDataReserva());
            linha[2] = reserva.getLaboratorio();
            linha[3] = "De " + converteHora.format(reserva.getHorarioEntradaReserva()) + " até " + converteHora.format(reserva.getHorarioSaidaReserva());
            linha[4] = reserva.getProposito();
            modelo.addRow(linha);
        }
        cp_tabelaReservas.setModel(modelo);
    }

    private void preencherTabelaFeedback(List<Feedback> Lista) {
        DefaultTableModel modelo = (DefaultTableModel) cp_tabelaFeedback.getModel();

        Object[] linha = new Object[5];

        modelo.setRowCount(0);
        for (Feedback feedback : Lista) {
            linha[0] = feedback.getSiape().getNome();
            linha[1] = feedback.getLaboratorio();
            linha[2] = converteData.format(feedback.getData());
            linha[3] = feedback.getDescricao();
            linha[4] = feedback.getStatus();
            modelo.addRow(linha);
        }
        cp_tabelaFeedback.setModel(modelo);
    }

    ControleFuncionario controleFuncionario = new ControleFuncionario();
    ControleReserva controleReserva = new ControleReserva();
    ControleFeedback controleFeedback = new ControleFeedback();
    SimpleDateFormat converteData = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat converteHora = new SimpleDateFormat("HH:mm");
    BancoFuncionario bancoFuncionario = new BancoFuncionario();
    ControleRelatorio controleRelatorio = new ControleRelatorio();
    Reserva reservaRecuperada;
    Feedback feedbackRecuperado;
}
