/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleFeedback;
import controller.ControleFuncionario;
import controller.ControleReserva;
import controller.ControleVariaveis;
import model.Reserva;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;
import model.Feedback;
import model.Funcionario;

/**
 *
 * @author edson
 */
public class TelaPrincipalFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalOutros
     */
    public TelaPrincipalFuncionario() {
        initComponents();
        iconeTitulo();
        tituloTabela();
        perguntarSair();
        corFundo();
        alterarReserva.setText("Alterar Reserva");
        cancelarReserva.setText("Cancelar Reserva");
        cancelarFeedback.setText("Remover Feedback");
        preencherTabelaReserva(controleReserva.pesquisar(""));
        preencherTabelaFeedback(controleFeedback.atualizar(""));
    }
        
    public void preencherTop(ControleVariaveis controleVariaveis) {
        txt_nomeFuncionarioConsFeedback.setText(controleVariaveis.getNomeTop());
        txt_nomeFuncionarioCadReserva.setText(controleVariaveis.getNomeTop());
        txt_nomeFuncionarioConsReserva.setText(controleVariaveis.getNomeTop());
        txt_nomeFuncionarioRealFeedback.setText(controleVariaveis.getNomeTop());
        txt_nomeFuncionarioOpcoes.setText(controleVariaveis.getNomeTop());
        txt_siapeConsFeedback.setText(controleVariaveis.getSiapeTop());
        txt_siapeCadReserva.setText(controleVariaveis.getSiapeTop());
        txt_siapeConsReserva.setText(controleVariaveis.getSiapeTop());
        txt_siapeRealFeedback.setText(controleVariaveis.getSiapeTop());
        txt_siapeOpcoes.setText(controleVariaveis.getSiapeTop());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuReserva = new javax.swing.JPopupMenu();
        cancelarReserva = new javax.swing.JMenuItem();
        alterarReserva = new javax.swing.JMenuItem();
        menuFeedback = new javax.swing.JPopupMenu();
        cancelarFeedback = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cp_proposito = new javax.swing.JTextPane();
        bt_cadastrarReserva = new javax.swing.JButton();
        bt_limparReserva = new javax.swing.JButton();
        cp_horaEntrada = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cp_minutoEntrada = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cp_horaSaida = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cp_minutoSaida = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cp_dataReserva = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        cp_laboratorioReserva = new javax.swing.JComboBox<>();
        txt_nomeFuncionarioCadReserva = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_siapeCadReserva = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cp_tabelaReservas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        bt_pesquisar = new javax.swing.JToggleButton();
        cp_pesquisar = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_nomeFuncionarioConsReserva = new javax.swing.JLabel();
        txt_siapeConsReserva = new javax.swing.JLabel();
        bt_atualizarTelaReserva = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cp_descricao = new javax.swing.JTextPane();
        bt_enviarFeedback = new javax.swing.JButton();
        bt_limparFeedback = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cp_laboratorio = new javax.swing.JComboBox<>();
        cp_assuntoFeedback = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_nomeFuncionarioRealFeedback = new javax.swing.JLabel();
        txt_siapeRealFeedback = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        cp_tabelaFeedback = new javax.swing.JTable();
        bt_atualizar = new javax.swing.JButton();
        txt_nomeFuncionarioConsFeedback = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_siapeConsFeedback = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        bt_voltarLogin = new javax.swing.JButton();
        bt_alterarCadastro = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_nomeFuncionarioOpcoes = new javax.swing.JLabel();
        txt_siapeOpcoes = new javax.swing.JLabel();

        cancelarReserva.setText("jMenuItem1");
        cancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarReservaActionPerformed(evt);
            }
        });
        menuReserva.add(cancelarReserva);
        cancelarReserva.getAccessibleContext().setAccessibleName("Cancelar Reserva");

        alterarReserva.setText("jMenuItem1");
        alterarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarReservaActionPerformed(evt);
            }
        });
        menuReserva.add(alterarReserva);

        cancelarFeedback.setText("jMenuItem1");
        cancelarFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarFeedbackActionPerformed(evt);
            }
        });
        menuFeedback.add(cancelarFeedback);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal - Control Lab");
        setExtendedState(this.MAXIMIZED_BOTH);

        jTabbedPane1.setFont(new java.awt.Font("GillSans", 0, 18)); // NOI18N

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preencha os campos abaixo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 15))); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 350));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel3.setText("h");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel4.setText("Horário de Saída:");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel5.setText("Propósito:");

        cp_proposito.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jScrollPane1.setViewportView(cp_proposito);

        bt_cadastrarReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_cadastrarReserva.setText("Cadastrar");
        bt_cadastrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarReservaActionPerformed(evt);
            }
        });

        bt_limparReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_limparReserva.setText("Limpar");
        bt_limparReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparReservaActionPerformed(evt);
            }
        });

        cp_horaEntrada.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_horaEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cp_horaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_horaEntradaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel17.setText("Horário de Entrada:");

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel18.setText("min");

        cp_minutoEntrada.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_minutoEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cp_minutoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_minutoEntradaActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel19.setText("h");

        cp_horaSaida.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_horaSaida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cp_horaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_horaSaidaActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel20.setText("min");

        cp_minutoSaida.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_minutoSaida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cp_minutoSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_minutoSaidaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel2.setText("Data da Reserva:");

        cp_dataReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel23.setText("Laboratório:");

        cp_laboratorioReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_laboratorioReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "Informática - BLOCO A", "Informática - BLOCO B", "Informática - BLOCO C", "Redes - BLOCO A" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cp_horaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cp_minutoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel23))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cp_horaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cp_minutoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 147, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(36, 36, 36)
                                .addComponent(cp_dataReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bt_cadastrarReserva)
                                .addGap(55, 55, 55)
                                .addComponent(bt_limparReserva)
                                .addGap(49, 49, 49))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(86, 86, 86)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cp_laboratorioReserva, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))))
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(cp_dataReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel17))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cp_horaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(cp_minutoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cp_horaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(cp_minutoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cp_laboratorioReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(115, 115, 115))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cadastrarReserva)
                            .addComponent(bt_limparReserva))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_nomeFuncionarioCadReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_nomeFuncionarioCadReserva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_nomeFuncionarioCadReserva.setText("Nome Completo do Funcionario");

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel25.setText("|");

        txt_siapeCadReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_siapeCadReserva.setText("1234567");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeBackground.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nomeFuncionarioCadReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_siapeCadReserva)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel7)
                        .addContainerGap(415, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nomeFuncionarioCadReserva)
                            .addComponent(jLabel25)
                            .addComponent(txt_siapeCadReserva))
                        .addGap(223, 223, 223)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(454, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Reserva", new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeCadastrarReserva.png")), jPanel1); // NOI18N

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fazer busca nas consultas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 15))); // NOI18N

        cp_tabelaReservas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cp_tabelaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data", "Laboratório", "Horário", "Propósito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cp_tabelaReservas.setToolTipText("");
        cp_tabelaReservas.setName(""); // NOI18N
        cp_tabelaReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cp_tabelaReservasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cp_tabelaReservas);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel9.setText("Pesquisar:");

        bt_pesquisar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        cp_pesquisar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_pesquisarActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel26.setText("|");

        txt_nomeFuncionarioConsReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_nomeFuncionarioConsReserva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_nomeFuncionarioConsReserva.setText("Nome Completo do Funcionario");

        txt_siapeConsReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_siapeConsReserva.setText("1234567");

        bt_atualizarTelaReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_atualizarTelaReserva.setText("Atualizar");
        bt_atualizarTelaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarTelaReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(cp_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(bt_pesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_atualizarTelaReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_nomeFuncionarioConsReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_siapeConsReserva)
                .addGap(24, 24, 24))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cp_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisar)
                    .addComponent(txt_nomeFuncionarioConsReserva)
                    .addComponent(jLabel26)
                    .addComponent(txt_siapeConsReserva)
                    .addComponent(bt_atualizarTelaReserva))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Consultar Reservas", new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeConsultarReservas.png")), jPanel3); // NOI18N

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preencha os campos abaixo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 15))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel15.setText("Descrição:");

        cp_descricao.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jScrollPane3.setViewportView(cp_descricao);

        bt_enviarFeedback.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_enviarFeedback.setText("Enviar");
        bt_enviarFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarFeedbackActionPerformed(evt);
            }
        });

        bt_limparFeedback.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_limparFeedback.setText("Limpar");
        bt_limparFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparFeedbackActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel10.setText("Laboratório:");

        cp_laboratorio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_laboratorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "Informática - BLOCO A", "Informática - BLOCO B", "Informática - BLOCO C", "Redes - BLOCO A" }));
        cp_laboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_laboratorioActionPerformed(evt);
            }
        });

        cp_assuntoFeedback.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        cp_assuntoFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_assuntoFeedbackActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel11.setText("Assunto:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_enviarFeedback)
                .addGap(55, 55, 55)
                .addComponent(bt_limparFeedback)
                .addGap(62, 62, 62))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cp_assuntoFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(47, 47, 47)
                        .addComponent(cp_laboratorio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cp_assuntoFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cp_laboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(41, 41, 41)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_limparFeedback)
                    .addComponent(bt_enviarFeedback))
                .addGap(29, 29, 29))
        );

        jLabel28.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel28.setText("|");

        txt_nomeFuncionarioRealFeedback.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_nomeFuncionarioRealFeedback.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_nomeFuncionarioRealFeedback.setText("Nome Completo do Funcionario");

        txt_siapeRealFeedback.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_siapeRealFeedback.setText("1234567");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeBackground.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addComponent(txt_nomeFuncionarioRealFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_siapeRealFeedback)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nomeFuncionarioRealFeedback)
                            .addComponent(jLabel28)
                            .addComponent(txt_siapeRealFeedback))
                        .addGap(210, 210, 210)
                        .addComponent(jLabel6)))
                .addContainerGap(472, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Realizar Feedback", new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeRealizarFeedback.png")), jPanel4); // NOI18N

        jScrollPane5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cp_tabelaFeedback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cp_tabelaFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Funcionário", "Laboratório", "Data", "Descrição", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cp_tabelaFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cp_tabelaFeedbackMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(cp_tabelaFeedback);

        bt_atualizar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_atualizar.setText("Atualizar");
        bt_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarActionPerformed(evt);
            }
        });

        txt_nomeFuncionarioConsFeedback.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_nomeFuncionarioConsFeedback.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_nomeFuncionarioConsFeedback.setText("Nome Completo do Funcionario");

        jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel29.setText("|");

        txt_siapeConsFeedback.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_siapeConsFeedback.setText("1234567");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_atualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 653, Short.MAX_VALUE)
                .addComponent(txt_nomeFuncionarioConsFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_siapeConsFeedback)
                .addGap(24, 24, 24))
            .addComponent(jScrollPane5)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nomeFuncionarioConsFeedback)
                        .addComponent(jLabel29)
                        .addComponent(txt_siapeConsFeedback))
                    .addComponent(bt_atualizar))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ConsultarFeedBack's", new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeFeedback.png")), jPanel6); // NOI18N

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecione alguma opção abaixo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 15))); // NOI18N

        bt_voltarLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_voltarLogin.setText("Sair");
        bt_voltarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarLoginActionPerformed(evt);
            }
        });

        bt_alterarCadastro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        bt_alterarCadastro.setText("Alterar Cadastro");
        bt_alterarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bt_voltarLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_alterarCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(bt_alterarCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(bt_voltarLogin)
                .addGap(155, 155, 155))
        );

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeBackground.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel27.setText("|");

        txt_nomeFuncionarioOpcoes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_nomeFuncionarioOpcoes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_nomeFuncionarioOpcoes.setText("Nome Completo do Funcionario");

        txt_siapeOpcoes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txt_siapeOpcoes.setText("1234567");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel24)
                        .addContainerGap(454, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nomeFuncionarioOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_siapeOpcoes)
                        .addGap(41, 41, 41))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nomeFuncionarioOpcoes)
                            .addComponent(jLabel27)
                            .addComponent(txt_siapeOpcoes))
                        .addGap(206, 206, 206)
                        .addComponent(jLabel24)))
                .addContainerGap(478, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Opções", new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconeOpcao.png")), jPanel10); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void iconeTitulo() {
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image imagem = kit.getImage(getClass().getResource("/view/imagens/logoTitulo.png"));
        setIconImage(imagem);
    }

    public void tituloTabela() {
        cp_tabelaReservas.getTableHeader().setFont(new Font("Arial Rounded MT Bold", 0, 15));
        cp_tabelaFeedback.getTableHeader().setFont(new Font("Arial Rounded MT Bold", 0, 15));
    }

    public void corFundo() {
        this.getContentPane().setBackground(new Color(102, 102, 102));

    }

    public void perguntarSair() {
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (e.getID() == WindowEvent.WINDOW_CLOSING) {
                    int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
                    if (selectedOption == JOptionPane.YES_OPTION) {
                        System.exit(0);
                    }
                }
            }
        });
    }

    private void bt_cadastrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarReservaActionPerformed
        // TODO add your handling code here:

        int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente cadastrar essa reserva?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {

            if (cp_dataReserva.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!!");
            }

            String siape = txt_siapeCadReserva.getText();
            String nome = txt_nomeFuncionarioCadReserva.getText();

            String msg = "";
            String proposito = cp_proposito.getText();
            String laboratorio = cp_laboratorioReserva.getSelectedItem().toString();

            Date auxDataReserva = cp_dataReserva.getDate();
            String aux2dataReserva = converteData.format(auxDataReserva);

            String horaEntrada = cp_horaEntrada.getSelectedItem().toString();
            String minutoEntrada = cp_minutoEntrada.getSelectedItem().toString();
            String horaSaida = cp_horaSaida.getSelectedItem().toString();
            String minutoSaida = cp_minutoSaida.getSelectedItem().toString();

            try {
                Date dataReserva = converteData.parse(aux2dataReserva);
                Date horarioEntradaReserva = converteHora.parse(horaEntrada + ":" + minutoEntrada);
                Date horarioSaidaReserva = converteHora.parse(horaSaida + ":" + minutoSaida);

                msg = controleReserva.cadastrar(nome, siape, dataReserva, horarioEntradaReserva, horarioSaidaReserva, proposito, laboratorio);
                JOptionPane.showMessageDialog(this, msg);

            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Data ou Hora inválidas!");
            }

            if (msg.equals("Reserva cadastrada com sucesso!")) {
                cp_dataReserva.setDate(null);
                cp_horaEntrada.setSelectedItem("--");
                cp_minutoEntrada.setSelectedItem("--");
                cp_horaSaida.setSelectedItem("--");
                cp_minutoSaida.setSelectedItem("--");
                cp_proposito.setText("");
                cp_laboratorioReserva.setSelectedItem("-------");
                List<Reserva> lista = controleReserva.pesquisar("");
                preencherTabelaReserva(lista);

            }

        }

    }//GEN-LAST:event_bt_cadastrarReservaActionPerformed

    private void bt_limparReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparReservaActionPerformed
        // TODO add your handling code here:

        cp_dataReserva.setDate(null);
        cp_horaEntrada.setSelectedItem("--");
        cp_minutoEntrada.setSelectedItem("--");
        cp_horaSaida.setSelectedItem("--");
        cp_minutoSaida.setSelectedItem("--");
        cp_proposito.setText("");
        cp_laboratorioReserva.setSelectedItem("-------");

    }//GEN-LAST:event_bt_limparReservaActionPerformed

    private void cp_horaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_horaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_horaEntradaActionPerformed

    private void cp_minutoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_minutoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_minutoEntradaActionPerformed

    private void cp_horaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_horaSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_horaSaidaActionPerformed

    private void cp_minutoSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_minutoSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_minutoSaidaActionPerformed

    private void cp_tabelaReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cp_tabelaReservasMouseClicked
        // TODO add your handling code here:

        DefaultTableModel modelo = (DefaultTableModel) cp_tabelaReservas.getModel();

        if (evt.getButton() == MouseEvent.BUTTON3 && cp_tabelaReservas.getSelectedRowCount() == 1) {
            try {
                int x = evt.getX();
                int y = evt.getY();

                int linha = cp_tabelaReservas.getSelectedRow();
                Date data = converteData.parse(modelo.getValueAt(linha, 1).toString());
                String horarioAux = modelo.getValueAt(linha, 3).toString();
                String nome = modelo.getValueAt(linha, 0).toString();

                Date horaEntrada = converteHora.parse(horarioAux.substring(3, 8));
                Date horaSaida = converteHora.parse(horarioAux.substring(13));

                if (nome.equals(txt_nomeFuncionarioCadReserva.getText())) {
                    menuReserva.show(cp_tabelaReservas, x, y);
                    reservaRecuperada = controleReserva.recuperarReserva(data, horaEntrada, horaSaida);
                } else {
                    JOptionPane.showMessageDialog(null, "Você não tem autorização de remover ou alterar essa reserva", "Control Lab Avisa", INFORMATION_MESSAGE);
                }

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro : " + erro, "Control Lab Avisa", ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cp_tabelaReservasMouseClicked

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        // TODO add your handling code here:

        String pesquisa = cp_pesquisar.getText();
        List<Reserva> Lista = controleReserva.pesquisar(pesquisa);
        preencherTabelaReserva(Lista);

    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void cp_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_pesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_pesquisarActionPerformed

    private void bt_enviarFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarFeedbackActionPerformed
        // TODO add your handling code here:

        int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente enviar esse Feedback?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {

            String assunto = cp_assuntoFeedback.getText();
            String laboratorio = cp_laboratorio.getSelectedItem().toString();
            String descricao = cp_descricao.getText();

            String siapeLogado = txt_siapeConsFeedback.getText();
            Funcionario funcionario = controleFuncionario.recuperar(siapeLogado);

            String msg = controleFeedback.salvar(assunto, laboratorio, descricao, funcionario);
            JOptionPane.showMessageDialog(this, msg);

            if (msg.equals("Feedback salvo com sucesso!")) {
                cp_assuntoFeedback.setText("");
                cp_laboratorio.setSelectedItem("-------");
                cp_descricao.setText("");
                List<Feedback> lista = controleFeedback.atualizar("");
                preencherTabelaFeedback(lista);
            }
        }

    }//GEN-LAST:event_bt_enviarFeedbackActionPerformed

    private void bt_limparFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparFeedbackActionPerformed
        // TODO add your handling code here:

        cp_laboratorio.setSelectedItem("-------");
        cp_descricao.setText("");
        cp_assuntoFeedback.setText("");

    }//GEN-LAST:event_bt_limparFeedbackActionPerformed

    private void cp_laboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_laboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_laboratorioActionPerformed

    private void cancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarReservaActionPerformed
        // TODO add your handling code here:

        int selectedOption = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar essa reserva?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {
            String msg = controleReserva.cancelarReserva(reservaRecuperada);
            JOptionPane.showMessageDialog(null, msg, "Control Lab Avisa", INFORMATION_MESSAGE);
            List<Reserva> lista = controleReserva.pesquisar("");
            preencherTabelaReserva(lista);
            cp_pesquisar.setText("");
        }

    }//GEN-LAST:event_cancelarReservaActionPerformed

    private void alterarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarReservaActionPerformed

        new TelaAlterarReserva(reservaRecuperada).setVisible(true);

    }//GEN-LAST:event_alterarReservaActionPerformed

    private void bt_alterarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarCadastroActionPerformed

        boolean administrador = false;
        new TelaAlterarCadastro(controleFuncionario.recuperar(txt_siapeCadReserva.getText()), administrador).setVisible(true);

    }//GEN-LAST:event_bt_alterarCadastroActionPerformed

    private void cp_tabelaFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cp_tabelaFeedbackMouseClicked
        
        DefaultTableModel modelo = (DefaultTableModel) cp_tabelaFeedback.getModel();

        if (evt.getButton() == MouseEvent.BUTTON3 && cp_tabelaFeedback.getSelectedRowCount() == 1) {
            try {
                int x = evt.getX();
                int y = evt.getY();

                int linha = cp_tabelaFeedback.getSelectedRow();
                
                String nomeFuncionario = modelo.getValueAt(linha, 0).toString();

                if (nomeFuncionario.equals(txt_nomeFuncionarioConsFeedback.getText())) {
                    menuFeedback.show(cp_tabelaFeedback, x, y);
                    feedbackRecuperado = controleFeedback.recuperarCancelarFeedback(linha);
                } else {
                    JOptionPane.showMessageDialog(null, "Você não tem autorização para remover esse feedback", "Control Lab Avisa", INFORMATION_MESSAGE);
                }

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro : " + erro, "Control Lab Avisa", ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_cp_tabelaFeedbackMouseClicked

    private void bt_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarActionPerformed
        // TODO add your handling code here:
        
        List<Feedback> lista = controleFeedback.atualizar("");
        preencherTabelaFeedback(lista);
        
    }//GEN-LAST:event_bt_atualizarActionPerformed

    private void bt_voltarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarLoginActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente voltar para a tela de login?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {
            dispose();
            new TelaLogin().setVisible(true);
        }
    }//GEN-LAST:event_bt_voltarLoginActionPerformed

    private void bt_atualizarTelaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarTelaReservaActionPerformed
        ControleVariaveis controleVariaveis = new ControleVariaveis();
        controleVariaveis.setNomeTop(txt_nomeFuncionarioConsFeedback.getText());
        controleVariaveis.setSiapeTop(txt_siapeConsFeedback.getText());

        TelaPrincipalFuncionario telaPrincipalFuncionario = new TelaPrincipalFuncionario();
        telaPrincipalFuncionario.preencherTop(controleVariaveis);
        telaPrincipalFuncionario.setVisible(true);

        dispose();
    }//GEN-LAST:event_bt_atualizarTelaReservaActionPerformed

    private void cp_assuntoFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_assuntoFeedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_assuntoFeedbackActionPerformed

    private void cancelarFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarFeedbackActionPerformed
        // TODO add your handling code here:
        
        int selectedOption = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar essa reserva?", "Control Lab Avisa", YES_NO_OPTION, QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {
            String msg = controleFeedback.removerFeedback(feedbackRecuperado);
            JOptionPane.showMessageDialog(null, msg, "Control Lab Avisa", INFORMATION_MESSAGE);
            preencherTabelaFeedback(controleFeedback.atualizar(""));
        }
        
    }//GEN-LAST:event_cancelarFeedbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarReserva;
    private javax.swing.JButton bt_alterarCadastro;
    private javax.swing.JButton bt_atualizar;
    private javax.swing.JToggleButton bt_atualizarTelaReserva;
    private javax.swing.JButton bt_cadastrarReserva;
    private javax.swing.JButton bt_enviarFeedback;
    private javax.swing.JButton bt_limparFeedback;
    private javax.swing.JButton bt_limparReserva;
    private javax.swing.JToggleButton bt_pesquisar;
    private javax.swing.JButton bt_voltarLogin;
    private javax.swing.JMenuItem cancelarFeedback;
    private javax.swing.JMenuItem cancelarReserva;
    private javax.swing.JTextField cp_assuntoFeedback;
    private com.toedter.calendar.JDateChooser cp_dataReserva;
    private javax.swing.JTextPane cp_descricao;
    private javax.swing.JComboBox<String> cp_horaEntrada;
    private javax.swing.JComboBox<String> cp_horaSaida;
    private javax.swing.JComboBox<String> cp_laboratorio;
    private javax.swing.JComboBox<String> cp_laboratorioReserva;
    private javax.swing.JComboBox<String> cp_minutoEntrada;
    private javax.swing.JComboBox<String> cp_minutoSaida;
    private javax.swing.JTextField cp_pesquisar;
    private javax.swing.JTextPane cp_proposito;
    private javax.swing.JTable cp_tabelaFeedback;
    private javax.swing.JTable cp_tabelaReservas;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPopupMenu menuFeedback;
    private javax.swing.JPopupMenu menuReserva;
    private javax.swing.JLabel txt_nomeFuncionarioCadReserva;
    private javax.swing.JLabel txt_nomeFuncionarioConsFeedback;
    private javax.swing.JLabel txt_nomeFuncionarioConsReserva;
    private javax.swing.JLabel txt_nomeFuncionarioOpcoes;
    private javax.swing.JLabel txt_nomeFuncionarioRealFeedback;
    private javax.swing.JLabel txt_siapeCadReserva;
    private javax.swing.JLabel txt_siapeConsFeedback;
    private javax.swing.JLabel txt_siapeConsReserva;
    private javax.swing.JLabel txt_siapeOpcoes;
    private javax.swing.JLabel txt_siapeRealFeedback;
    // End of variables declaration//GEN-END:variables

    private void preencherTabelaReserva(List<Reserva> Lista) {
        DefaultTableModel modelo = (DefaultTableModel) cp_tabelaReservas.getModel();

        Object[] linha = new Object[5];

        modelo.setRowCount(0);
        for (Reserva reserva : Lista) {
            linha[0] = reserva.getSiape().getNome();
            linha[1] = converteData.format(reserva.getDataReserva());
            linha[2] = reserva.getLaboratorio();
            linha[3] = "De " + converteHora.format(reserva.getHorarioEntradaReserva()) + " até " + converteHora.format(reserva.getHorarioSaidaReserva());
            linha[4] = reserva.getProposito();

            modelo.addRow(linha);
        }
        cp_tabelaReservas.setModel(modelo);
    }
    
    private void preencherTabelaFeedback(List<Feedback> Lista) {
        DefaultTableModel modelo = (DefaultTableModel) cp_tabelaFeedback.getModel();

        Object[] linha = new Object[5];

        modelo.setRowCount(0);
        for (Feedback feedback : Lista) {
            linha[0] = feedback.getSiape().getNome();
            linha[1] = feedback.getLaboratorio();
            linha[2] = converteData.format(feedback.getData());
            linha[3] = feedback.getDescricao();
            linha[4] = feedback.getStatus();
            modelo.addRow(linha);
        }
        cp_tabelaFeedback.setModel(modelo);
    }
    
    
    ControleFuncionario controleFuncionario = new ControleFuncionario();
    ControleReserva controleReserva = new ControleReserva();
    ControleFeedback controleFeedback = new ControleFeedback();
    SimpleDateFormat converteData = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat converteHora = new SimpleDateFormat("HH:mm");
    Reserva reservaRecuperada;
    Feedback feedbackRecuperado;
}
